apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-efs-storage 
provisioner: eks-prod/aws-efs
parameters:
  archiveOnDelete: "true"
reclaimPolicy: Retain # 当删除pvc的时候，对应的存储卷不回收
allowVolumeExpansion: true # 使得pvc可以在线扩容
